// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, Client, TDataShape } from "./client";
import type {
  ActionDetectionSignToTextData,
  ActionDetectionSignToTextResponses,
  ActionDetectionSignToTextErrors,
  ActionDetectionModelInfoData,
  ActionDetectionModelInfoResponses,
  ActionDetectionTextToSignData,
  ActionDetectionTextToSignResponses,
  ActionDetectionTextToSignErrors,
  ActionDetectionSaveDatasetSequenceData,
  ActionDetectionSaveDatasetSequenceResponses,
  ActionDetectionSaveDatasetSequenceErrors,
  HealthHealthCheckData,
  HealthHealthCheckResponses,
} from "./types.gen";
import { client } from "./client.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Sign To Text
 */
export const actionDetectionSignToText = <ThrowOnError extends boolean = false>(
  options: Options<ActionDetectionSignToTextData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ActionDetectionSignToTextResponses,
    ActionDetectionSignToTextErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/v1/action-detection/sign-to-text",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Model Info
 */
export const actionDetectionModelInfo = <ThrowOnError extends boolean = false>(
  options?: Options<ActionDetectionModelInfoData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ActionDetectionModelInfoResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/v1/action-detection/model-info",
    ...options,
  });
};

/**
 * Text To Sign
 */
export const actionDetectionTextToSign = <ThrowOnError extends boolean = false>(
  options: Options<ActionDetectionTextToSignData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ActionDetectionTextToSignResponses,
    ActionDetectionTextToSignErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/v1/action-detection/text-to-sign",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Save Dataset Sequence
 */
export const actionDetectionSaveDatasetSequence = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ActionDetectionSaveDatasetSequenceData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ActionDetectionSaveDatasetSequenceResponses,
    ActionDetectionSaveDatasetSequenceErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/v1/action-detection/dataset",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Health Check
 */
export const healthHealthCheck = <ThrowOnError extends boolean = false>(
  options?: Options<HealthHealthCheckData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    HealthHealthCheckResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/health",
    ...options,
  });
};
